services:

  mysql8:
    image: mysql:8.3-oracle
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: [
      "mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--innodb_file_per_table=0",
      "--innodb_doublewrite=0",
      "--skip-name-resolve"
    ]
    volumes:
      - mysql8:/var/lib/mysql

volumes:
  mysql8:
    driver_opts:
      type: tmpfs
      device: tmpfs
